// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTrNuGEBih_YbsZxZHXKkJEfQu8GjVJU',
    appId: '1:947152569948:web:7a2700d24cde0a50cbc899',
    messagingSenderId: '947152569948',
    projectId: 'prueba-fwitter',
    authDomain: 'prueba-fwitter.firebaseapp.com',
    databaseURL: 'https://prueba-fwitter-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-fwitter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrWkiR8OtLBcumY20uJwqjZXbBPlO6qBg',
    appId: '1:947152569948:android:f38b8a75eefd01a7cbc899',
    messagingSenderId: '947152569948',
    projectId: 'prueba-fwitter',
    databaseURL: 'https://prueba-fwitter-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-fwitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPLzbuy35erUXW73FMC1GPLHgQoMZAXM0',
    appId: '1:947152569948:ios:fd513c31fcad4b40cbc899',
    messagingSenderId: '947152569948',
    projectId: 'prueba-fwitter',
    databaseURL: 'https://prueba-fwitter-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-fwitter.appspot.com',
    iosClientId: '947152569948-9doa19ml92rcekb3v6f4jt1f2ck5tol5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPLzbuy35erUXW73FMC1GPLHgQoMZAXM0',
    appId: '1:947152569948:ios:d5262a04d84d0084cbc899',
    messagingSenderId: '947152569948',
    projectId: 'prueba-fwitter',
    databaseURL: 'https://prueba-fwitter-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-fwitter.appspot.com',
    iosClientId: '947152569948-ssi3g1n9vr87ab5bpv222ruci61rjvk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseConnection.RunnerTests',
  );
}
